#!/usr/bin/env python3
"""Embed the CREngine stylesheets (cr3.css, epub.css, html5.css) into
cre_css.h as a single concatenated string for crossnook-cre-test.cpp.

Deterministic: nothing but file order changes the output.
Usage: embed-css.py <out.h>
"""
import sys

from pathlib import Path

ORDER = ("cr3.css", "epub.css", "html5.css")
HERE = Path(__file__).parent


def main() -> None:
    out = Path(sys.argv[1])
    parts = []
    for name in ORDER:
        data = (HERE / name).read_text(encoding="utf-8")
        parts.append(f"/* ---- {name} ---- */\n")
        parts.append(data)
        if not data.endswith("\n"):
            parts.append("\n")
    body = "".join(parts).encode("utf-8")
    # escape raw bytes (>=0x80 stay as literal UTF-8 bytes in the literal)
    esc = []
    for b in body:
        if b == 0x5C:      # backslash
            esc.append("\\\\")
        elif b == 0x22:    # double quote
            esc.append('\\"')
        elif b < 0x20 or b == 0x7F:
            esc.append("\\%03o" % b)
        else:
            esc.append(chr(b))
    esc = "".join(esc)
    lines = []
    cur = ""
    for ch in esc:
        cur += ch
        if len(cur) >= 60 and not ch == "\\":
            lines.append(f'    "{cur}"')
            cur = ""
    if cur:
        lines.append(f'    "{cur}"')
    head = (
        "/* generated by embed-css.py from the cr3.css/epub.css/html5.css fixtures. Do not edit */\n"
        "static const char cre_css[] =\n"
    )
    with open(out, "w", encoding="latin-1", newline="\n") as f:
        f.write(head + "\n".join(lines) + ";\n")
    print(f"wrote {out} ({len(body)} css bytes)")


if __name__ == "__main__":
    main()